export const ListCitySigla = [
    { nome: 'Acre', sigla: 'AC', ibge: 12 },
    { nome: 'Alagoas', sigla: 'AL', ibge: 27 },
    { nome: 'Amapá', sigla: 'AP', ibge: 16 },
    { nome: 'Amazonas', sigla: 'AM', ibge: 13 },
    { nome: 'Bahia', sigla: 'BA', ibge: 29 },
    { nome: 'Ceará', sigla: 'CE', ibge: 23 },
    { nome: 'Distrito Federal', sigla: 'DF', ibge: 53 },
    { nome: 'Espírito Santo', sigla: 'ES', ibge: 32 },
    { nome: 'Goiás', sigla: 'GO', ibge: 52 },
    { nome: 'Maranhão', sigla: 'MA', ibge: 21 },
    { nome: 'Mato Grosso', sigla: 'MT', ibge: 51 },
    { nome: 'Mato Grosso do Sul', sigla: 'MS', ibge: 50 },
    { nome: 'Minas Gerais', sigla: 'MG', ibge: 31 },
    { nome: 'Pará', sigla: 'PA', ibge: 15 },
    { nome: 'Paraíba', sigla: 'PB', ibge: 25 },
    { nome: 'Paraná', sigla: 'PR', ibge: 41 },
    { nome: 'Pernambuco', sigla: 'PE', ibge: 26 },
    { nome: 'Piauí', sigla: 'PI', ibge: 22 },
    { nome: 'Rio de Janeiro', sigla: 'RJ', ibge: 33 },
    { nome: 'Rio Grande do Norte', sigla: 'RN', ibge: 24 },
    { nome: 'Rio Grande do Sul', sigla: 'RS', ibge: 43 },
    { nome: 'Rondônia', sigla: 'RO', ibge: 11 },
    { nome: 'Roraima', sigla: 'RR', ibge: 14 },
    { nome: 'Santa Catarina', sigla: 'SC', ibge: 42 },
    { nome: 'São Paulo', sigla: 'SP', ibge: 35 },
    { nome: 'Sergipe', sigla: 'SE', ibge: 28 },
    { nome: 'Tocantins', sigla: 'TO', ibge: 17 }
];
